version: "3.3"
services:
  frontend:
    image: koma00/quasar_dev:latest
    ports:
      - "8080:8080"
    volumes:
      - "./frontend/src:/home/node/quasar/src"
      - "./frontend/public:/home/node/quasar/public"
    depends_on:
      - api
  api:
    build: ./backend
    command: bash -c "
        sleep 10
        && python manage.py migrate
        && python manage.py initadmin --username=admin --email=admin@example.com --password=admin
        && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - "./backend:/code"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"