version: "3.3"
services:
  frontend:
    image: koma00/quasar_dev:latest
    ports:
      - "8080:8080"
    volumes:
      - "./frontend/src:/home/node/quasar/src"
      - "./frontend/public:/home/node/quasar/public"